name : Deploy 
on : 
  push :
   branches :
   - main
jobs :
 ssh_deploy:
  name: to always data
  runs-on: ubuntu-latest
  steps :
  - uses: actions/checkout@v3
  - name : ssh-connect
    uses : appleboy/ssh-action@v0.1.10
    with : 
      host : {{ secrets.ALWAYS_DATA_SSH_HOST}}
      username : {{ secrets.ALWAYS_DATA_USER_NAME }}
      password : {{ secrets.ALWAYS_DATA_SSH_PASSWORD }}
      script: git pull
    
